### ISSUE TITLE
coord1 in 1D Plotting with Plots undefined

### ISSUE THREAD

**Issue by Anemometer** [j-fu/ExtendableGrids.jl#1]
The coordinate extraction in the `isplots(Plotter)` case makes use of the undefined expression `coord1` in
https://github.com/j-fu/ExtendableGrids.jl/blob/ce822ed8a2f398bc586dec8015a08838e3fc7ce1/src/plot.jl#L145
which throws a `ERROR: UndefVarError: coord1 not defined`.

This should probably be replaced with 
```
x1=coord[cellnodes[1,icell]]
x2=coord[cellnodes[2,icell]]
```
The same goes for 
https://github.com/j-fu/ExtendableGrids.jl/blob/ce822ed8a2f398bc586dec8015a08838e3fc7ce1/src/plot.jl#L155
where
`x1=coord1[1,bfacenodes[1,ibface]]`
should probably be replaced with
`x1=coord[bfacenodes[1,ibface]]`.

**Comment by j-fu** [comment]
thanks - sure, fixed in v0.2.3 Unfortunately there  is no easy way to test these things automatically.
